version: "1"
rules:
  - base: main                        # Required. Target branch
    upstream: nixos/nixpkgs:master    # Required. Must be in the same fork network.
    mergeMethod: merge                # Optional, one of [none, merge, squash, rebase, hardreset], Default: none.
    conflictReviewers:                # Optional, on merge conflict assign a reviewer
      - tennox
# label: ":arrow_heading_down: pull"  # Optional
conflictLabel: "upstream-conflict"     # Optional, on merge conflict assign a custom label, Default: merge-conflict


